- Aesop/Rule.lean
Lean4 no longer allows `←` in pure code.
> chore: update lean4

- Aesop/Builder/Forward.lean
- Aesop/RuleTac/Forward.lean
This is all extracted from my lab course experiment, I can try to synthesize test cases if you want. The last commit is less clear-cut, it could be argued that it should at least be restricted to `reducible` transparency (though Lean itself usually applies it at `default` afaik).
> Various forward rules improvements

- lakefile.lean
The half-enabled releases only cause warnings downstream.
> `warning: wanted prebuilt release, but release repository and tag was not known`
> Completely disable prebuilt releases

- .github/workflows/build.yml
- Aesop/Builder/Basic.lean
- Aesop/Check.lean
- Aesop/Options.lean
- Aesop/RuleTac/Basic.lean
- Aesop/RuleTac/Forward.lean
- Aesop/Script.lean
- Aesop/Search/Queue.lean
- Aesop/Tracing.lean
- Aesop/Tracing/Init.lean
- Aesop/Util/Basic.lean
- Aesop/Util/Tactic.lean
- Aesop/Util/UnionFind.lean
- tests/run/Aesop.lean
`import Std` makes it really hard to try changes in std4 when debugging things in mathlib4.  This is only going to get worse as Mario moves all of mathlib into std.
> Remove blanket imports of Std or Lean

- Aesop/Search/SearchM.lean
- Aesop/Tree/TreeM.lean
- Aesop/Util/Basic.lean
I've also removed all the other priority annotations on instances.  Those were unnecessary and just gave a false sense of utility.  Don't use instance priorities unless you absolutely know what you're doing, can clearly explain why they're necessary, have verified that it doesn't work without, and added a comment documenting that fact!
> Remove overlapping BEq instance

- README.md
Going off the syntax for removing a rule from a rule set, this seems to be the syntax for adding an aesop rule about an imported declaration to a rule set. If I'm wrong, please let me know what the preferred method is (if there is one). Also minor edits for distinguishing the 'adding/removing' sections of the README.
> doc: adding external declars to rule sets

- Aesop/Builder.lean
- Aesop/Builder/Basic.lean
- Aesop/Builder/Default.lean
- Aesop/Builder/NormSimp.lean
- Aesop/Builder/Unfold.lean
- Aesop/Frontend/RuleExpr.lean
- Aesop/Profiling.lean
- Aesop/Rule.lean
- Aesop/RuleSet.lean
- Aesop/Script.lean
- Aesop/Search/Expansion.lean
- Aesop/Search/Expansion/Simp/Basic.lean
- Aesop/Search/Expansion/Simp/SimpGoal.lean
- Aesop/Util/Tactic.lean
- README.md
- tests/run/23.lean
- tests/run/DocLists.lean
- tests/run/List.lean
- tests/run/Unfold.lean
@Kha I finally got around to fixing the smart unfolding issue. A `simp` rule for a declaration `d` now adds `d` to the `simp` set like `@[simp] d` would. An `unfold` rule for `d` now unfolds `d` without smart unfolding.
`unfold` rules are implemented by a new `simp` pass in the normalisation phase, inspired by the `simp` used in the `unfold` tactic. The implementation is in `Aesop/Util/Tactic.lean`. Could you maybe take a look at this? (The rest of this PR is just scaffolding.)
One question is whether the `unfold` `simp` pass should recurse into the unfolded expressions. The `unfold` tactic does not do this, but as a result, it may miss unfoldable expressions, depending on the order of its arguments. So I'm tempted to allow such recursion. The downside is that `unfold` then cannot be used …
> Add unfold builder

- Aesop/BuiltinRules/DestructProducts.lean
- Aesop/BuiltinRules/Split.lean
- Aesop/BuiltinRules/Subst.lean
- Aesop/Frontend/Attribute.lean
- Aesop/Frontend/Command.lean
- Aesop/Frontend/RuleExpr.lean
- Aesop/Frontend/Tactic.lean
- Aesop/Script.lean
- Aesop/Tracing.lean
- Aesop/Util/Tactic.lean
- AesopTest/Forward.lean
- AesopTest/RuleSetNameHygiene1.lean
Adds spaces to affect the pretty printing of the `aesop` tactic.
> Fix spacing in grammar

- AesopTest/List.lean
- lake-manifest.json
- lean-toolchain
Because there is a new `lake-manifest.json` version number, downstream dependencies (e.g. Mathlib) can't bump to the latest master until this is merged.
> chore: bump to nightly-2023-08-16

- README.md
The README mentions option `trace.aesop.finalTree`, which does not seem to exist. I'm assuming the option referenced at that point in the README is now called `tree`.
> Update README.md `trace.aesop.finalTree` => `trace.aesop.tree`

- Aesop/Options/Public.lean
- Aesop/Search/Expansion/Norm.lean
Future-proofing for leanprover/lean4#2722. A comment on `SimpConfig` is missing but I didn't exactly know what to write.
> chore: adapt to `decide := false` in simp

- Aesop/Script.lean
- Aesop/Search/Queue.lean
- Aesop/Util/UnionFind.lean
This is a pre-patch for [std4#379](https://github.com/leanprover/std4/pull/379). It only replaces some imports by more precise ones. It is intended to be applied *before* std4#379, that will prevent breakage if and when that PR happens and it is otherwise completely harmless for aesop.
> chore: fix imports

- Aesop/Search/Expansion.lean
- Aesop/Util/Basic.lean
The fields of Subarray are changing in the next Lean release.
The function `Aesop.Subarray.popFront` can be replaced by `Subarray.popHead?` in the meantime.
> fix: account for lean4#3851

- Aesop/Builder/Forward.lean
- Aesop/RuleTac/Forward.lean
- Aesop/Tree/UnsafeQueue.lean
- Aesop/Util/UnorderedArraySet.lean
In preparation for https://github.com/leanprover/lean4/pull/3969 landing, we fix some deprecation warnings.
> chore: fix deprecations hidden by dot notation

- .github/workflows/build.yml
Convert existing CI to use `lean-action`.
I did a test run of the workflow on my fork [here](https://github.com/austinletson/aesop/actions/runs/9063431865/job/24899356289?pr=1)
Additional CI features added through lean-action:
- .lake caching across runs
- check reservoir eligibility
> chore: switch to lean-action

- Aesop/Search/Main.lean
- Aesop/Util/Basic.lean
- AesopTest/RulePattern.lean
- AesopTest/SafePrefixExpansionRappLimit.lean
- AesopTest/SafePrefixInTerminalError.lean
- AesopTest/TerminalError.lean
- AesopTest/TraceProof.lean
When in terminal mode, print the (first) goal after the terminal prefix as part of the error message, so we get an indication of what progress aesop made, and where it got stuck.
Too often I write a structure where some auto_param field is not successfully filled in by `aesop`, and it's presumably just because a `@[simp]` lemma is missing. But to see the goal (and hence deduce the missing simp lemma), I have to add ` field := by aesop`. I think with this change we'll just be able to see what we need immediately.
> feat: print first goal after safe prefix in terminal mode

- .github/workflows/build.yml
add `actions/checkout` as this was removed from `lean-action` in `v1-beta`
> chore: upgrade `lean-action` to `v1-beta`

- Aesop/Script/SpecificTactics.lean
- AesopTest/ScriptWithOptions.lean
See https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/aesop.20try.20this.20regression
> Script.SpecificTactics: fix generated `simp (config := ...)` syntax

- Aesop/Builder/Forward.lean
- Aesop/RulePattern.lean
- Aesop/RuleTac/Forward.lean
- Aesop/Script/StructureDynamic.lean
- Aesop/Script/StructureStatic.lean
- Aesop/Script/Util.lean
- Aesop/Search/Expansion.lean
The automation can find them anyway, and indeed these occurrences break when I try out changes to `Std.Range` (but the automation still works).
> chore: remove unnecessary explicit indexing proofs

- Aesop/Stats/Extension.lean
- AesopTest/Stats.lean
The stats extension had the wrong async mode, leading to panics.
> Stats.Extension: fix panics due to async elaboration

- Aesop/RuleTac/GoalDiff.lean
- Aesop/Util/EqualUpToIds.lean
This PR makes changes for compatibility with https://github.com/leanprover/lean4/pull/8804.
The key difference is that `nondep := true` should be treated as a cdecl in the future. The `LocalDecl.isLet` function will return false for such ldecls.
> refactor: avoid using `LocalDecl` constructors directly

- Aesop/Forward/RuleInfo.lean
- Aesop/Forward/State.lean
- Aesop/RPINF.lean
- Aesop/RPINF/Basic.lean
- Aesop/RuleTac/Forward.lean
- AesopTest/ForwardInstanceTransparency.lean
- AesopTest/ForwardTransparency.lean
- AesopTest/SaturatePerformance.lean
Forward reasoning did not work with instances that are defeq at `instances`
transparency, but not at `reducible` transparency. This is common, so we want
to support it.
> Forward/RPINF: use reducible+instances transparency
